# Generated by Django 5.2.11 on 2026-02-07 04:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Examen',
                'verbose_name_plural': 'Exámenes',
            },
        ),
        migrations.CreateModel(
            name='ExamenCandidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fecha_presentacion', models.DateTimeField(auto_now_add=True)),
                ('completado', models.BooleanField(default=False)),
                ('tiempo_empleado', models.DurationField(blank=True, null=True)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examenes_presentados', to=settings.AUTH_USER_MODEL)),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatos', to='app_examen.examen')),
            ],
            options={
                'verbose_name': 'Examen Candidato',
                'verbose_name_plural': 'Exámenes Candidatos',
                'unique_together': {('candidato', 'examen')},
            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField(max_length=400)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='preguntas/')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='preguntas', to='app_examen.examen')),
            ],
            options={
                'verbose_name': 'Pregunta',
                'verbose_name_plural': 'Preguntas',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField(max_length=400)),
                ('es_correcta', models.BooleanField(default=False)),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='respuestas', to='app_examen.pregunta')),
            ],
            options={
                'verbose_name': 'Respuesta',
                'verbose_name_plural': 'Respuestas',
            },
        ),
        migrations.CreateModel(
            name='RespuestaCandidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_correcta', models.BooleanField(default=False)),
                ('fecha_respuesta', models.DateTimeField(auto_now_add=True)),
                ('examen_candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_dadas', to='app_examen.examencandidato')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_examen.pregunta')),
                ('respuesta_seleccionada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_examen.respuesta')),
            ],
            options={
                'verbose_name': 'Respuesta del Candidato',
                'verbose_name_plural': 'Respuestas de los Candidatos',
                'unique_together': {('examen_candidato', 'pregunta')},
            },
        ),
    ]
