# Generated by Django 5.2.11 on 2026-02-15 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_examen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examencandidato',
            name='examen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examenes_candidatos', to='app_examen.examen'),
        ),
    ]
