# Generated by Django 5.2.11 on 2026-02-15 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_examen', '0002_alter_examencandidato_examen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examencandidato',
            options={'verbose_name': '📊 Historial de Examen Presentado', 'verbose_name_plural': '📊 Historial de Exámenes Presentados'},
        ),
        migrations.AlterModelOptions(
            name='respuestacandidato',
            options={'verbose_name': '🔍 Auditoría de Respuesta Individual', 'verbose_name_plural': '🔍 Auditoría de Respuestas Individuales'},
        ),
    ]
